
import static javax.swing.BorderFactory.createTitledBorder;
import javax.swing.JOptionPane;


/**
 *
 * @author x535
 */
public class Actividad1 extends javax.swing.JFrame {

    /**
     * Creates new form Actividad1
     */
    public Actividad1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Conversor = new javax.swing.ButtonGroup();
        error = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        dSalir = new javax.swing.JButton();
        gradosIzquierda = new javax.swing.JLabel();
        gradosDerecha = new javax.swing.JLabel();
        realizar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        inputGrados = new javax.swing.JTextField();
        outputGrados = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lista = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        gradosC = new javax.swing.JRadioButton();
        gradosF = new javax.swing.JRadioButton();
        gradosK = new javax.swing.JRadioButton();

        error.setMinimumSize(new java.awt.Dimension(347, 229));

        jLabel1.setText("Error");

        dSalir.setText("Salir");
        dSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout errorLayout = new javax.swing.GroupLayout(error.getContentPane());
        error.getContentPane().setLayout(errorLayout);
        errorLayout.setHorizontalGroup(
            errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dSalir)
                    .addComponent(jLabel1))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        errorLayout.setVerticalGroup(
            errorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(dSalir)
                .addGap(90, 90, 90))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor");

        gradosIzquierda.setText("º F");

        gradosDerecha.setText("ºK");

        realizar.setText("Realizar");
        realizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("A º Celsius"));

        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Farenheit", "Kelvin" }));
        lista.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Convierte de º Farenheit"));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        Conversor.add(gradosC);
        gradosC.setText("º Celsius");
        gradosC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gradosCItemStateChanged(evt);
            }
        });

        Conversor.add(gradosF);
        gradosF.setText("º Farenheit");
        gradosF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gradosFItemStateChanged(evt);
            }
        });

        Conversor.add(gradosK);
        gradosK.setText("º Kelvin");
        gradosK.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gradosKItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gradosC)
                    .addComponent(gradosF)
                    .addComponent(gradosK))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradosC)
                .addGap(18, 18, 18)
                .addComponent(gradosF)
                .addGap(18, 18, 18)
                .addComponent(gradosK)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(realizar)
                .addGap(44, 44, 44)
                .addComponent(limpiar)
                .addGap(37, 37, 37)
                .addComponent(salir)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(inputGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gradosIzquierda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(outputGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gradosDerecha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gradosIzquierda)
                    .addComponent(inputGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputGrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradosDerecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(realizar)
                    .addComponent(limpiar)
                    .addComponent(salir))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void realizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarActionPerformed
        double numeroGrados=0;
        double operacion;
        
        if(gradosC.isSelected()){
           numeroGrados=Integer.parseInt(inputGrados.getText());
           if(lista.getSelectedItem().equals("Kelvin")){
               operacion=numeroGrados+273.15;
               outputGrados.setText(operacion+"");
           }else if(lista.getSelectedItem().equals("Farenheit")){
                operacion=((numeroGrados*9)/5)+32;
                outputGrados.setText(operacion+"");
           }
           
        }else if(gradosF.isSelected()){
           numeroGrados=Integer.parseInt(inputGrados.getText());
           if(lista.getSelectedItem().equals("Celsius")){
               operacion=((numeroGrados-32)*5)/9;
               outputGrados.setText(operacion+"");
           }else if(lista.getSelectedItem().equals("Kelvin")){
               operacion=(((numeroGrados-32)*5)/9)+273.15;
               outputGrados.setText(operacion+"");
           }
           
        }else{
           numeroGrados=Integer.parseInt(inputGrados.getText());
           if(lista.getSelectedItem().equals("Celsius")){
                operacion=numeroGrados-273.15 ;
                outputGrados.setText(operacion+"");
           }else if(lista.getSelectedItem().equals("Farenheit")){
                operacion=(((numeroGrados-273.15)*9)/5)+32 ;
                outputGrados.setText(operacion+"");
           }
        }
        
        
        
    }//GEN-LAST:event_realizarActionPerformed

    private void gradosCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gradosCItemStateChanged
        gradosIzquierda.setText("ºC");
        jPanel1.setBorder(createTitledBorder("Convierte de º Celsius"));

    }//GEN-LAST:event_gradosCItemStateChanged

    private void gradosFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gradosFItemStateChanged
        gradosIzquierda.setText("ºF");
        jPanel1.setBorder(createTitledBorder("Convierte de º Farenheit"));
    }//GEN-LAST:event_gradosFItemStateChanged

    private void gradosKItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gradosKItemStateChanged
        gradosIzquierda.setText("ºK");
        jPanel1.setBorder(createTitledBorder("Convierte de º Kelvin"));


    }//GEN-LAST:event_gradosKItemStateChanged

    private void listaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaItemStateChanged
        if(lista.getSelectedItem().equals("Celsius")){
            jPanel2.setBorder(createTitledBorder("A º Celsius"));
            gradosDerecha.setText("º C");
            outputGrados.setText(null);
        }else if(lista.getSelectedItem().equals("Kelvin")){
            jPanel2.setBorder(createTitledBorder("A º Kelvin"));
            gradosDerecha.setText("º K");
            outputGrados.setText(null);
        }else{
            jPanel2.setBorder(createTitledBorder("A º Farenheit"));
            gradosDerecha.setText("º F");
            outputGrados.setText(null);
        }
        
    }//GEN-LAST:event_listaItemStateChanged

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        inputGrados.setText(null);
        outputGrados.setText(null);
        gradosC.setSelected(true);

        inputGrados.requestFocus();
    }//GEN-LAST:event_limpiarActionPerformed

    private void dSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dSalirActionPerformed
        error.setVisible(false);
    }//GEN-LAST:event_dSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Conversor;
    private javax.swing.JButton dSalir;
    private javax.swing.JDialog error;
    private javax.swing.JRadioButton gradosC;
    private javax.swing.JLabel gradosDerecha;
    private javax.swing.JRadioButton gradosF;
    private javax.swing.JLabel gradosIzquierda;
    private javax.swing.JRadioButton gradosK;
    private javax.swing.JTextField inputGrados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton limpiar;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JTextField outputGrados;
    private javax.swing.JButton realizar;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
