
import static java.lang.Thread.sleep;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x505
 */
public class Ahorcado extends javax.swing.JFrame {
           
    ArrayList<String> palabras;
    String palabraJuego;
    boolean juegoIniciado;
    int intentos;
    String palabraProvisional="";
    char[] arrayLetras;
    /**
     * Creates new form Ahorcado
     */
    public Ahorcado() {
        initComponents();
        palabras = new ArrayList();
        juegoIniciado=false;
        intentos= 0;

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoAddPalabra = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        tfAddPalabras = new javax.swing.JTextField();
        botonAdd = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfPalabra = new javax.swing.JTextField();
        tfLetra = new javax.swing.JTextField();
        tfIntentos = new javax.swing.JTextField();
        botonIntroducirPalabras = new javax.swing.JButton();
        botonJugar = new javax.swing.JButton();
        botonFinalizar = new javax.swing.JButton();

        dialogoAddPalabra.setMinimumSize(new java.awt.Dimension(382, 195));

        jLabel4.setText("Palabra:");

        botonAdd.setText("Añadir");
        botonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoAddPalabraLayout = new javax.swing.GroupLayout(dialogoAddPalabra.getContentPane());
        dialogoAddPalabra.getContentPane().setLayout(dialogoAddPalabraLayout);
        dialogoAddPalabraLayout.setHorizontalGroup(
            dialogoAddPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAddPalabraLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(dialogoAddPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoAddPalabraLayout.createSequentialGroup()
                        .addComponent(botonAdd)
                        .addGap(57, 57, 57)
                        .addComponent(botonSalir))
                    .addGroup(dialogoAddPalabraLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(tfAddPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        dialogoAddPalabraLayout.setVerticalGroup(
            dialogoAddPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAddPalabraLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(dialogoAddPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAddPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(dialogoAddPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAdd)
                    .addComponent(botonSalir))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Palabra");

        jLabel2.setText("Letra");

        jLabel3.setText("Intentos");

        tfPalabra.setEditable(false);

        tfLetra.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tfLetraPropertyChange(evt);
            }
        });
        tfLetra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfLetraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLetraKeyReleased(evt);
            }
        });

        tfIntentos.setEditable(false);

        botonIntroducirPalabras.setText("Introducir palabras");
        botonIntroducirPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIntroducirPalabrasActionPerformed(evt);
            }
        });

        botonJugar.setText("Jugar");
        botonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJugarActionPerformed(evt);
            }
        });

        botonFinalizar.setText("Finalizar");
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonIntroducirPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tfLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(botonJugar)
                        .addGap(18, 18, 18)
                        .addComponent(botonFinalizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIntroducirPalabras)
                    .addComponent(botonJugar)
                    .addComponent(botonFinalizar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIntroducirPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIntroducirPalabrasActionPerformed
        dialogoAddPalabra.setVisible(true);
        
    }//GEN-LAST:event_botonIntroducirPalabrasActionPerformed

    private void botonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddActionPerformed
        palabras.add(tfAddPalabras.getText());
        tfAddPalabras.setText(null);
        
    }//GEN-LAST:event_botonAddActionPerformed

    private void botonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJugarActionPerformed
        if(palabras.size()>0){
            juegoIniciado=true;
            intentos=5;
            tfIntentos.setText(intentos+"");
            palabraJuego= palabras.get((int)(Math.random()*palabras.size()));
            String huecos="";
            for (int i = 0; i < palabraJuego.length(); i++) {
                huecos+="_ ";
                palabraProvisional+="_";
            }
            tfPalabra.setText(huecos);
            arrayLetras=palabraProvisional.toCharArray();
        }else{
            System.err.println("Estás equivocado, no puedes jugar sin palabras.");
        }
    }//GEN-LAST:event_botonJugarActionPerformed

    private void tfLetraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tfLetraPropertyChange
        
    }//GEN-LAST:event_tfLetraPropertyChange

    private void tfLetraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLetraKeyPressed

    }//GEN-LAST:event_tfLetraKeyPressed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dialogoAddPalabra.setVisible(false);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void tfLetraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLetraKeyReleased
        String recogerLetra =tfLetra.getText();        
        if (intentos>0) {
        try{
            
                
            
       boolean palabraEncontrada=false;
        for (int i = 0; i < palabraJuego.length(); i++) {
           
            if (palabraJuego.charAt(i)==recogerLetra.charAt(0)) {
                arrayLetras[i]=recogerLetra.charAt(0);
                palabraEncontrada=true;
            }
        }
            if (!palabraEncontrada) {
                intentos--;
                tfIntentos.setText(intentos+"");
                if(intentos<1){
                    System.err.println("Has agotado los intentos, no puedes jugar");
                }
            }
        sleep(1000);
        tfLetra.setText(null);
        String otraPalabra="";
            for (int i = 0; i < arrayLetras.length; i++) {
                otraPalabra+=arrayLetras[i];
            }
        tfPalabra.setText(otraPalabra);
        }catch(Exception e){}
        }

    }//GEN-LAST:event_tfLetraKeyReleased

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdd;
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JButton botonIntroducirPalabras;
    private javax.swing.JButton botonJugar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JDialog dialogoAddPalabra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tfAddPalabras;
    private javax.swing.JTextField tfIntentos;
    private javax.swing.JTextField tfLetra;
    private javax.swing.JTextField tfPalabra;
    // End of variables declaration//GEN-END:variables
}
