/*
TO DO:
densidad de palabras
imagenes
    alt
    titulos
    cantidad
    tama;o total de imagen
si tiene videos,
✔longitud de encabezados (ME FALTA MOSTRAR LA VARIABLE)
✔longitud de parrafos

caracteres totales 
✔info pagina
    ✔titulo
    ✔meta descripcion
    ✔lenguaje

Análisis TF/IDF
Href follow no follow ugc....
Canonical
keywords
la bandera del idioma (hreflang)?
tiene robots.txt?

enlaces
    externos
    internos
    follow
    no follow
    enlaces rotos
✔(problema: suman mas de 20)   palabras totales
✔ n` de javascriptses

*/
import com.vdurmont.emoji.EmojiParser;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author java_
 */
public class AnalizarWeb extends javax.swing.JFrame {
    Document doc;
    Metodos sacarWeb;
    ContarPalabras sacarKeywords;
    /**
     * Creates new form NewJFrame
     */
    public AnalizarWeb() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ponerTexto = new javax.swing.JTextArea();
        analizarWeb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        website = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        setH1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        setH2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        setH3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        setH4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        palabrasTotales = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        javascriptTotales = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buscarKeywords = new javax.swing.JButton();
        opcionPalabras = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        metadescripcion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lenguaje = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        multimedia = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ponerTexto.setColumns(20);
        ponerTexto.setRows(5);
        jScrollPane1.setViewportView(ponerTexto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 810, 264));

        analizarWeb.setText("Analizar Web");
        analizarWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarWebActionPerformed(evt);
            }
        });
        getContentPane().add(analizarWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 13, -1, -1));

        jLabel1.setText("Website:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 17, -1, -1));
        getContentPane().add(website, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 14, 211, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        jLabel2.setText("H1:");

        setH1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        setH1.setForeground(new java.awt.Color(255, 127, 0));
        setH1.setText("0");

        jLabel10.setText("H2:");

        setH2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        setH2.setForeground(new java.awt.Color(255, 127, 0));
        setH2.setText("0");

        jLabel12.setText("H3:");

        setH3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        setH3.setForeground(new java.awt.Color(255, 127, 0));
        setH3.setText("0");

        jLabel14.setText("H4:");

        setH4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        setH4.setForeground(new java.awt.Color(255, 127, 0));
        setH4.setText("0");

        jButton1.setText("Cuenta las palabras");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Palabras totales: ");

        palabrasTotales.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        palabrasTotales.setForeground(new java.awt.Color(255, 127, 0));
        palabrasTotales.setText("0");

        jLabel4.setText("Javascript:");

        javascriptTotales.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        javascriptTotales.setForeground(new java.awt.Color(255, 127, 0));
        javascriptTotales.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palabrasTotales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(setH1)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(setH2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(setH3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(setH4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(javascriptTotales)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(javascriptTotales)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(setH4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(setH3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(setH2)
                        .addComponent(setH1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(palabrasTotales)))
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 520, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("KeyWords"));

        buscarKeywords.setText("Buscar keywords");
        buscarKeywords.setEnabled(false);
        buscarKeywords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarKeywordsActionPerformed(evt);
            }
        });

        opcionPalabras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 palabra", "2 palabras", "3 palabras", "4 palabras" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarKeywords)
                .addGap(18, 18, 18)
                .addComponent(opcionPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarKeywords)
                    .addComponent(opcionPalabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 270, 70));

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane2.setViewportView(texto);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 237, 810, 264));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Multimedia"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, 100));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("MetaDescripcion"));

        jLabel6.setText("Titulo: ");

        titulo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 127, 0));
        titulo.setText("0");

        metadescripcion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        metadescripcion.setForeground(new java.awt.Color(255, 127, 0));
        metadescripcion.setText("0");

        jLabel7.setText("MetaDescripcion:");

        lenguaje.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lenguaje.setForeground(new java.awt.Color(255, 127, 0));
        lenguaje.setText("0");

        jLabel8.setText("Lenguaje:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lenguaje, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(metadescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(metadescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lenguaje))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, -1, 330));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Media de palabras"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 430, -1, 200));

        multimedia.setText("Multimedia");
        jMenuBar1.add(multimedia);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analizarWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarWebActionPerformed
       sacarWeb= new Metodos(website.getText());
       jButton1.setEnabled(true);
       analizarWeb.setEnabled(false);
       buscarKeywords.setEnabled(true);
       
    }//GEN-LAST:event_analizarWebActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//    sacarWeb.verEncabezados(setH1, setH2, setH3, setH4, ponerTexto);
//    sacarWeb.verBody(palabrasTotales);
//    sacarWeb.verJavascript(javascriptTotales);
//    sacarWeb.metaDescripcion(titulo,metadescripcion,lenguaje);
      //sacarWeb.mediadePalabras();
      sacarWeb.mediadeEncabezados();
    //sacarWeb.verRobotsTxt();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscarKeywordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarKeywordsActionPerformed
        sacarKeywords= new ContarPalabras(ponerTexto.getText(), texto);
        sacarKeywords.SepararPalabras(opcionPalabras);
        sacarKeywords.ordenarDatos();

    }//GEN-LAST:event_buscarKeywordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalizarWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalizarWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalizarWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalizarWeb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalizarWeb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizarWeb;
    private javax.swing.JButton buscarKeywords;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel javascriptTotales;
    private javax.swing.JLabel lenguaje;
    private javax.swing.JLabel metadescripcion;
    private javax.swing.JMenu multimedia;
    private javax.swing.JComboBox<String> opcionPalabras;
    private javax.swing.JLabel palabrasTotales;
    private javax.swing.JTextArea ponerTexto;
    private javax.swing.JLabel setH1;
    private javax.swing.JLabel setH2;
    private javax.swing.JLabel setH3;
    private javax.swing.JLabel setH4;
    private javax.swing.JTextArea texto;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField website;
    // End of variables declaration//GEN-END:variables
}
