/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x535
 */
import java.awt.MenuShortcut;
import java.awt.event.*;
public class GUI09 extends java.awt.Frame {

    /**
     * Creates new form GUI09
     */
    public GUI09() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menuItem1 = new java.awt.MenuItem();
        menuItem2 = new java.awt.MenuItem();
        menu4 = new java.awt.Menu();
        menuItem3 = new java.awt.MenuItem();
        menuItem4 = new java.awt.MenuItem();
        menu2 = new java.awt.Menu();
        menuItem5 = new java.awt.MenuItem();
        menuItem6 = new java.awt.MenuItem();
        menu5 = new java.awt.Menu();
        menu3 = new java.awt.Menu();

        setPreferredSize(new java.awt.Dimension(500, 200));
        setTitle("Ejemplo de menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        menuBar1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N

        menu1.setLabel("Entrada 1");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });

        menuItem1.setLabel("SubEntrada 1 1");
        menu1.add(menuItem1);
        menu1.addSeparator();
        menuItem2.setLabel("SubEntrada 1 2");
        menuItem2.setShortcut(new java.awt.MenuShortcut(java.awt.event.KeyEvent.VK_E)
        );
        menu1.add(menuItem2);

        menu4.setLabel("SubEntrada 1 3");

        menuItem3.setLabel("SubEntrada 1 3 1");
        menu4.add(menuItem3);

        menuItem4.setLabel("SubEntrada 1 3 2");
        menu4.add(menuItem4);

        menu1.add(menu4);

        menuBar1.add(menu1);

        menu2.setLabel("Entrada 2");

        menuItem5.setLabel("Subentrada2 1");
        menu2.add(menuItem5);
        menu2.addSeparator();
        menuItem6.setLabel("SubEntrada2 2");
        menuItem6.setShortcut(new java.awt.MenuShortcut(KeyEvent.VK_W));
        menu2.add(menuItem6);

        menu5.setLabel("SubEntrada2 3");
        menu2.add(menu5);

        menuBar1.add(menu2);

        menu3.setLabel("Ayuda");
        menuBar1.add(menu3);

        setMenuBar(menuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI09().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuItem menuItem1;
    private java.awt.MenuItem menuItem2;
    private java.awt.MenuItem menuItem3;
    private java.awt.MenuItem menuItem4;
    private java.awt.MenuItem menuItem5;
    private java.awt.MenuItem menuItem6;
    // End of variables declaration//GEN-END:variables
}
