/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x535
 */
public class GUI07 extends java.awt.Frame {

    /**
     * Creates new form GUI07
     */
    public GUI07() {
        initComponents();
        for(int i=1; i<=4;i++){
            listaEste.add("Lista-"+i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSur = new java.awt.Panel();
        textField1 = new java.awt.TextField();
        checkbox1 = new java.awt.Checkbox();
        lista = new java.awt.Choice();
        panelOeste = new java.awt.Panel();
        boton1 = new java.awt.Button();
        boton2 = new java.awt.Button();
        panelCentro = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        textCentro = new java.awt.TextArea();
        panelEste = new java.awt.Panel();
        listaEste = new java.awt.List();

        setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        setName(""); // NOI18N
        setTitle("Ejemplo07");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        panelSur.setPreferredSize(new java.awt.Dimension(234, 50));

        textField1.setMinimumSize(new java.awt.Dimension(110, 19));
        textField1.setText("Campo de texto");
        panelSur.add(textField1);

        checkbox1.setLabel("CheckBox");
        panelSur.add(checkbox1);

        lista.setName(""); // NOI18N
        panelSur.add(lista);
        lista.add("Manolo");

        add(panelSur, java.awt.BorderLayout.SOUTH);

        panelOeste.setMinimumSize(new java.awt.Dimension(0, 70));
        panelOeste.setLayout(new java.awt.GridLayout(2, 1));

        boton1.setActionCommand("Boton1");
        boton1.setLabel("Boton1");
        boton1.setPreferredSize(new java.awt.Dimension(80, 70));
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        panelOeste.add(boton1);
        boton1.getAccessibleContext().setAccessibleName("Boton1");

        boton2.setActionCommand("Boton2");
        boton2.setLabel("Boton2");
        boton2.setPreferredSize(new java.awt.Dimension(80, 70));
        panelOeste.add(boton2);
        boton2.getAccessibleContext().setAccessibleName("Boton2");

        add(panelOeste, java.awt.BorderLayout.WEST);

        panelCentro.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Etiqueta");
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 30));
        panelCentro.add(jLabel1, java.awt.BorderLayout.NORTH);

        textCentro.setEditable(false);
        textCentro.setText("Area de texto");
        panelCentro.add(textCentro, java.awt.BorderLayout.CENTER);

        add(panelCentro, java.awt.BorderLayout.CENTER);

        panelEste.setLayout(new java.awt.GridLayout(1, 0));

        listaEste.setPreferredSize(new java.awt.Dimension(80, 80));
        panelEste.add(listaEste);
        for(int i=5;i<=10;i++){
            listaEste.add("Lista-"+i);
        }

        add(panelEste, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI07().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button boton1;
    private java.awt.Button boton2;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JLabel jLabel1;
    private java.awt.Choice lista;
    private java.awt.List listaEste;
    private java.awt.Panel panelCentro;
    private java.awt.Panel panelEste;
    private java.awt.Panel panelOeste;
    private java.awt.Panel panelSur;
    private java.awt.TextArea textCentro;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
