/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author x535
 */
import java.awt.*;
import java.awt.event.*;
public class GUI10 extends java.awt.Frame {

    /**
     * Creates new form GUI10
     */
    public GUI10() {
        initComponents();
        bAceptar.addActionListener(new BotonAceptar());
        bCerrar.addActionListener(new BotonCancelar());
    }
    class BotonAceptar implements ActionListener{
        public void actionPerformed(ActionEvent e){
            Etiqueta.setText("Boton Aceptar pulsado");
        }
    }
    class BotonCancelar implements ActionListener{
        public void actionPerformed(ActionEvent e){
            Etiqueta.setText("Boton Cancelar pulsado.");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAceptar = new java.awt.Button();
        bCerrar = new java.awt.Button();
        Etiqueta = new java.awt.Label();

        setPreferredSize(new java.awt.Dimension(300, 300));
        setTitle("Manolo es el mejor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new java.awt.FlowLayout());

        bAceptar.setLabel("Aceptar");
        add(bAceptar);

        bCerrar.setLabel("Cerrar");
        bCerrar.setPreferredSize(new java.awt.Dimension(65, 23));
        add(bCerrar);

        Etiqueta.setText("label1");
        add(Etiqueta);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI10().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Etiqueta;
    private java.awt.Button bAceptar;
    private java.awt.Button bCerrar;
    // End of variables declaration//GEN-END:variables
}
